
_default:
 @just --list

[unix]
run *flags:
  LD_PRELOAD=/lib/x86_64-linux-gnu/libssl.so.3:/lib/x86_64-linux-gnu/libcrypto.so.3 \
  lua -l src/setup src/main.lua {{ flags }}

install *flags:
  luarocks install --deps-only {{ flags }} lib_http-dev-1.rockspec
