_default:
    @just --list --unsorted

clean:
    rm *.exe -f
    rm *.class -f
    rm *.uc -f
    rm classes -rf

m := "fib"

[unix]
build:
    #!/usr/bin/env bash
    set -uxo pipefail

    cc {{ m }}.c -O3 -o {{ m }}_c.exe && strip $_
    c3c compile {{ m }}.c3 -O3 -o {{ m }}_c3.exe && strip $_
    chicken-csc {{ m }}.ss -static -fixnum-arithmetic -O3 -o {{ m }}_chicken.exe && strip $_ && rm *.link -f
    mkdir -p classes && clj -Sdeps '{:paths ["."]}' -M -e '(compile (quote {{ m }}))'
    crystal build {{ m }}.cr --release -o {{ m }}_crystal.exe && strip $_
    dart compile exe {{ m }}.dart -o {{ m }}_dart.exe && chmod +x $_
    go build -o {{ m }}_go.exe {{ m }}.go && strip {{ m }}_go.exe
    ghc --make {{ m }}.hs -fllvm -O -o {{ m }}_haskell.exe && strip $_ && rm {{ m }}.hi -f
    javac {{ m }}.java
    nim c --hints:off -d:release -o:{{ m }}_nim.exe {{ m }}.nim && strip {{ m }}_nim.exe
    ocamlopt {{ m }}.ml -O3 -o {{ m }}_ocaml.exe && strip $_ && rm {{ m }}.cm{i,x} -f
    # FIXME: not libpolyml static-linking now
    polyc {{ m }}.sml -o {{ m }}_poly.exe && strip $_
    if [ "Android" != "$(uname -o)" ]; then
      # Ada
      (
        cat <<'EOF' > alire.toml
    name = "demo"
    description = ""
    version = "0.1.0-dev"

    authors = ["Your Name"]
    maintainers = ["Your Name <example@example.com>"]
    licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
    website = ""
    tags = []

    executables = ["demo"]
    EOF
        eval $(alr printenv) && gnatmake {{ m }}.adb -O3 -o {{ m }}_ada.exe && strip $_ && rm {{ m }}.{ali,o} alire -rf 
        rm alire.toml -f
      )
      # Koka
      koka {{ m }}.kk -v0 -O3 -o {{ m }}_koka.exe && strip $_ && chmod +x $_ && rm .koka -rf
      # Moonbit
      moon run {{ m }}.mbt --target native --release && cp _build/native/release/build/single/single.exe {{ m }}_moon.exe && strip $_ && rm _build -rf
      # Pony    
      ponyc -b {{ m }}_pony.exe && strip $_
      # Racket CS
      raco make {{ m }}.rkt && raco demodularize -o {{ m }}.zo {{ m }}.rkt && raco exe --cs --orig-exe -o {{ m }}_racket.exe {{ m }}.zo && strip {{ m }}_racket.exe && rm ./compiled {{ m }}.zo -rf
      # Unison
      ucm << 'EOF'
    project.create {{ m }}
    load {{ m }}.u
    update
    compile main {{ m }}
    EOF
      # Roc
      roc build {{ m }}.roc --optimize --output {{ m }}_roc.exe && strip $_
      # Zig
      zig build-exe {{ m }}.zig -O ReleaseFast && mv {{ m }} {{ m }}_zig.exe && strip $_
    fi
    rustc {{ m }}.rs -O -o {{ m }}_rust.exe && strip $_
    sbcl --script {{ m }}.lisp
    swiftc {{ m }}.swift -static-stdlib -O -o {{ m }}_swift.exe && strip $_
    v {{ m }}.v -prod -o {{ m }}_v.exe && strip $_
    rm *.o -f

warmup := "3"
natives := `rg --files --sort=path -g '*.exe' | rg -U '(.+)\n' -r './$1 ' || true`
scripts := f"./{{m}}.jl ./{{m}}.ts ./{{m}}.lua ./{{m}}.ss"
clojure_cp := `clj -Spath || true`
clojure := f"java -Xmx8m -Xms8m -XX:TieredStopAtLevel=1 -cp ./classes:{{clojure_cp}} {{m}}"
java := f"java -Xmx8m -Xms8m -XX:TieredStopAtLevel=1 {{m}}"
unison := f"ucm run.compiled {{m}}.uc"
bytecodes := f"'{{clojure}}' '{{java}}' '{{unison}}'"

[group('bench')]
bench_all:
    hyperfine --warmup {{ warmup }} {{ natives }} {{ scripts }} {{ bytecodes }}

[group('bench')]
bench_natives:
    hyperfine --warmup {{ warmup }} {{ natives }}

[group('bench')]
bench_scripts:
    hyperfine --warmup {{ warmup }} {{ scripts }}

[group('bench')]
bench_bytecodes:
    hyperfine --warmup {{ warmup }} {{ bytecodes }}
