_default:
    @just --list --unsorted

exe-info executable:
    ls -l {{ executable }}
    file {{ executable }}
    ldd {{ executable }}

add-json-deps:
    dart pub add json_annotation dev:build_runner dev:json_serializable

gen:
    dart run build_runner build --delete-conflicting-outputs

gen-watch:
    dart run build_runner watch --delete-conflicting-outputs

test:
    dart test

run:
    dart run imgur ./棋魂.jpg

exe:
    dart compile exe bin/imgur.dart -o imgur.exe && chmod +x imgur.exe
    just exe-info imgur.exe
