_default:
    @just --list --unsorted

add_json_deps:
    dart pub add json_annotation dev:build_runner dev:json_serializable

gen:
    dart run build_runner build --delete-conflicting-outputs

gen_watch:
    dart run build_runner watch --delete-conflicting-outputs

test:
    dart test

run:
    dart run imgur ./棋魂.jpg

exe:
    dart compile exe bin/imgur.dart -o imgur.exe && chmod +x imgur.exe
