@BASE_URI = "https://httpbin.org"


### GET_IP

GET {{BASE_URI}}/ip HTTP/1.1
Accept: application/json


### POST_JSON

POST {{BASE_URI}}/post HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "foo": [
    "bar",
    "baz"
  ]
}


### POST_FORMDATA

POST {{BASE_URI}}/post HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

custname=foo&
custtel=123&
custemail=foo@123.com&
size=small&
topping=bacon&
topping=cheese&
delivery=20:30&
comments=roc


### POST_MULTIPART

POST https://api.imgur.com/3/image?client_id=546c25a59c58ad7 HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{$timestamp}}
Referer: https://imgur.com/

------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="image"; filename="file.png"
Content-Type: image/jpeg

< ./file.png

------WebKitFormBoundary{{$timestamp}}--
