project_path := justfile_directory()
project_name := file_name(project_path)
sbcl_cmd := "sbcl --noinform --noprint --disable-debugger"

_default:
    @just --list --unsorted

[group('ql')]
ql-setup:
    #!/usr/bin/env bash
    set -euxo pipefail

    curl -O https://beta.quicklisp.org/quicklisp.lisp
    sbcl --load quicklisp.lisp <<EOF
    (quicklisp-quickstart:install)
    (ql:add-to-init-file)
    (quit)
    EOF
    rm quicklisp.lisp

[group('ql')]
ql-update:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (ql:update-client :prompt nil)
    EOF

[group('dist')]
dist-search KEYWORD:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (ql:system-apropos {{ KEYWORD }}) 
    EOF

[group('dist')]
dist-install DIST:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (ql:quickload {{ DIST }}) 
    EOF

[group('dist')]
dist-uninstall DIST:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (ql:uninstall {{ DIST }}) 
    EOF

[group('dist')]
dist-update DIST:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (ql:update-dist {{ DIST }} :prompt nil)
    EOF

[group('dist')]
dist-update-all:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (ql:update-all-dists :prompt nil)
    EOF

[group('asdf-project')]
init:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (ql:quickload :cl-project)
    (cl-project:make-project #p"../{{ project_name }}"
      :name "{{ project_name }}"
      :description "{{ project_name }}"
      :author "lost"
      :license "MIT"
      :depends-on '())
    EOF
    echo "Finishing cl-project:make-project ..."

    echo "Creating .sbclrc ..."
    cat <<EOF > .sbclrc
    (push (truename ".") asdf:*central-registry*)
    EOF

    echo "Creating dev.lisp ..."
    cat <<EOF > dev.lisp
    (load ".sbclrc")
    (ql:quickload :{{ project_name }})
    (asdf:load-system :{{ project_name }})
    EOF

[group('asdf-project')]
sync:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (load ".sbclrc")
    (ql:quickload :{{ project_name }})
    (asdf:load-system :{{ project_name }})
    EOF

[group('asdf-project')]
run FUN="main" *ARGS:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (load ".sbclrc")
    (ql:quickload :{{ project_name }})
    (asdf:load-system :{{ project_name }})
    ({{ project_name }}:{{ FUN }} {{ ARGS }})
    EOF

[group('asdf-project')]
test:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (load ".sbclrc")
    (ql:quickload :{{ project_name }}/tests)
    (asdf:test-system :{{ project_name }}/tests)
    EOF

[group('asdf-project')]
make:
    #!/usr/bin/env bash
    set -euxo pipefail

    cat <<EOF   
    # NOTE: please ensure these build configs on ASD file

        :build-operation "program-op"
        :build-pathname "demo.exe"
        :entry-point "demo:main"

    EOF

    {{ sbcl_cmd }} <<EOF
    (load ".sbclrc")
    (asdf:make :{{ project_name }})
    EOF

[group('asdf-project')]
build ENTRYPOINT_FUN="main":
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (load ".sbclrc")
    (ql:quickload :{{ project_name }})
    (asdf:load-system :{{ project_name }})
    (sb-ext:save-lisp-and-die "{{ project_name }}.exe"
      :executable t
      :toplevel #'{{ project_name }}:{{ ENTRYPOINT_FUN }}
      :compression 9
      :save-runtime-options t)
    EOF

[group('single-file')]
single-file-init NAME:
    #!/usr/bin/env bash
    set -euxo pipefail

    file="{{ NAME }}.lisp"

    if [[ -e "$file" ]]; then
      echo "Error: $file already exists" >&2
      exit 1
    fi

    cat <<EOF > $file
    (defun main ()
      (format t "~A~&" "Hello SBCL."))
    EOF

[group('single-file')]
single-file-run FILE FUN="main" *ARGS:
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (load "{{ FILE }}")
    ({{ FUN }} {{ ARGS }})
    EOF

[group('single-file')]
single-file-build FILE ENTRYPOINT_FUN="main":
    #!/usr/bin/env bash
    set -euxo pipefail

    {{ sbcl_cmd }} <<EOF
    (load "{{ FILE }}")
    (sb-ext:save-lisp-and-die "{{ file_stem(FILE) }}.exe"
      :executable t
      :toplevel #'{{ ENTRYPOINT_FUN }}
      :compression 9
      :save-runtime-options t)
    EOF

[group('script')]
script-init NAME:
    #!/usr/bin/env bash
    set -euxo pipefail

    file="{{ NAME }}.lisp"

    if [[ -e "$file" ]]; then
      echo "Error: $file already exists" >&2
      exit 1
    fi

    cat <<EOF > $file
    #!/usr/bin/env -S sbcl --script
    (format t "~A~&" "Hello SBCL script.")
    EOF

    chmod +x $file

[group('coalton')]
coalton-init:
    #!/usr/bin/env bash
    set -euxo pipefail

    echo "Creating .sbclrc ..."
    cat <<'EOF' > .sbclrc
    (push (truename ".") asdf:*central-registry*)
    EOF
    echo "Creating dev.lisp ..."
    cat << 'EOF' > dev.lisp
    (load ".sbclrc")

    (let ((config '((:compiler-mode                   "development")
                    (:print-unicode                   t)
                    (:perform-specialization          nil)
                    (:perform-heuristic-inlining      nil)
                    (:emit-type-annotations           nil)
                    (:print-types                     t)
                    (:print-rewrites                  nil)
                    (:auto-continue-redefinition      t)
                    (:deprecation-warnings-as-errors  nil))))
      (setf (symbol-plist ':coalton-config) nil)
      (loop :for (key value) :in config
            :do (setf (get ':coalton-config key) value)))

    (asdf:load-system "{{ project_name }}")
    EOF
    echo  "Creating build.lisp ..." 
    cat <<'EOF' > build.lisp
    (load ".sbclrc")

    (let ((config '((:compiler-mode                 "release")
                    (:print-unicode                 t)
                    (:perform-specialization        t)
                    (:perform-heuristic-inlining    t)
                    (:emit-type-annotations         t)
                    (:print-types                   t)
                    (:print-rewrites                t))))
      (setf (symbol-plist ':coalton-config) nil)
      (loop :for (key value) :in config
            :do (setf (get ':coalton-config key) value)))

    (asdf:load-system "{{ project_name }}")

    #+sbcl
     (sb-ext:save-lisp-and-die "{{ project_name }}.exe"
                               :toplevel #'{{ project_name }}:main
                               :executable t
                               :compression 9)

    EOF
    echo "Creating ASDF file ..."
    cat <<'EOF' > {{ project_name }}.asd
    (defsystem "{{ project_name }}"
      :defsystem-depends-on ("coalton-asdf")
      :depends-on ("coalton")
      :serial t
      :components ((:ct-file "main")))
    EOF
    echo "Creating main.ct ..."
    cat << 'EOF' > main.ct
    (defpackage #:{{ project_name }}
      (:use #:coalton #:coalton-prelude)
      (:export #:main))

    (in-package #:{{ project_name }})

    (coalton-toplevel

      (declare main (Void -> Void))
      (define (main)
        (print "HELLO COALTON.")))
    EOF

[group('coalton')]
coalton-single-file-init NAME:
    #!/usr/bin/env bash
    set -euxo pipefail

    file="{{ NAME }}.ct"

    if [[ -e "$file" ]]; then
      echo "Error: $file already exists" >&2
      exit 1
    fi

    cat << 'EOF' > $file
    (defpackage #:{{ NAME }}
      (:use #:coalton #:coalton-prelude)
      (:export #:main))

    (in-package #:{{ NAME }})

    (named-readtables:in-readtable coalton:coalton)

    (coalton-toplevel

     (declare main (Void -> Void))
     (define (main)
        (print "HELLO COALTON.")))

    #+sbcl
     (sb-ext:save-lisp-and-die "{{ NAME }}.exe"
                               :toplevel #'main
                               :executable cl:t
                               :compression 9)

    EOF

[group('coalton')]
coalton-single-file-build FILE:
    COALTON_ENV=release sbcl --noinform --eval '(asdf:load-system "coalton")' --load {{ FILE }}
