_default:
    @just --list --unsorted

# get alias list
alias-list:
    clj -X:deps aliases

# get dep version
deps-version lib_name:
    clj -X:deps find-versions :lib {{ lib_name }}

# get deps list
deps-list:
    clj -X:deps list

# get deps tree
deps-tree:
    clj -X:deps tree

# run main-fn with babashka
bb *args:
    bb -m demo.core {{ args }}

# run main-fn with clj
run *args:
    clj -M:run {{ args }}

# run tests
test:
    clj -X:test
