set windows-shell := ["powershell", "-nologo", "-noprofile", "-c"]

_default:
    @just --list --unsorted

# list used flutter widgets
[unix]
widget:
    rg -g '*.cljd' '[\[\(\s](m/\w+)' . -oIN -r '$1' | sort | uniq -c | sort -k3n | tee /dev/tty | wc -l

# list used flutter widgets
[windows]
widget:
    rg -g '*.cljd' '[\[\(\s](m/\w+)' . -oIN -r '$1' | group -noelement | sort count | tee -variable $output | measure -line

# show hard-coded numbers
num:
    rg -g '*.cljd' '[\s\(\[]\d+(\.\d+)?' .

# show hard-coded strings
str:
    # \s\s* - remove fn description
    rg -g '*.cljd' '\S\s*".+"' . | rg log -v
