_default:
    @just --list --unsorted

exe-info executable:
    ls -l {{ executable }}
    file {{ executable }}
    ldd {{ executable }}

run:
    swift run

test-http:
    hurl test.hurl

BUILD_OPTIONS := "-c release --product proxy_server --static-swift-stdlib -Xlinker /data/data/com.termux/files/usr/lib/libandroid-posix-semaphore.a"

build:
    swift build {{ BUILD_OPTIONS }}
    cp -f "$(swift build {{ BUILD_OPTIONS }} --show-bin-path)/proxy_server" .
    just exe-info proxy_server
